//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *AutoUpdateSpec) DeepCopyInto(out *AutoUpdateSpec) {
	*out = *in
}

func (in *AutoUpdateSpec) DeepCopy() *AutoUpdateSpec {
	if in == nil {
		return nil
	}
	out := new(AutoUpdateSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ExposeSpec) DeepCopyInto(out *ExposeSpec) {
	*out = *in
}

func (in *ExposeSpec) DeepCopy() *ExposeSpec {
	if in == nil {
		return nil
	}
	out := new(ExposeSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *GarageCluster) DeepCopyInto(out *GarageCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *GarageCluster) DeepCopy() *GarageCluster {
	if in == nil {
		return nil
	}
	out := new(GarageCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *GarageCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GarageClusterList) DeepCopyInto(out *GarageClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GarageCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GarageClusterList) DeepCopy() *GarageClusterList {
	if in == nil {
		return nil
	}
	out := new(GarageClusterList)
	in.DeepCopyInto(out)
	return out
}

func (in *GarageClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GarageClusterSpec) DeepCopyInto(out *GarageClusterSpec) {
	*out = *in
	out.AutoUpdate = in.AutoUpdate
	in.Storage.DeepCopyInto(&out.Storage)
	out.Config = in.Config
	out.Expose = in.Expose
	if in.RPCSecretRef != nil {
		in, out := &in.RPCSecretRef, &out.RPCSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.AdminTokenRef != nil {
		in, out := &in.AdminTokenRef, &out.AdminTokenRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GarageClusterSpec) DeepCopy() *GarageClusterSpec {
	if in == nil {
		return nil
	}
	out := new(GarageClusterSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *GarageClusterStatus) DeepCopyInto(out *GarageClusterStatus) {
	*out = *in
	if in.LastUpdateCheck != nil {
		in, out := &in.LastUpdateCheck, &out.LastUpdateCheck
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GarageClusterStatus) DeepCopy() *GarageClusterStatus {
	if in == nil {
		return nil
	}
	out := new(GarageClusterStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *GarageConfigSpec) DeepCopyInto(out *GarageConfigSpec) {
	*out = *in
}

func (in *GarageConfigSpec) DeepCopy() *GarageConfigSpec {
	if in == nil {
		return nil
	}
	out := new(GarageConfigSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *GarageWebUI) DeepCopyInto(out *GarageWebUI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *GarageWebUI) DeepCopy() *GarageWebUI {
	if in == nil {
		return nil
	}
	out := new(GarageWebUI)
	in.DeepCopyInto(out)
	return out
}

func (in *GarageWebUI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GarageWebUIList) DeepCopyInto(out *GarageWebUIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GarageWebUI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GarageWebUIList) DeepCopy() *GarageWebUIList {
	if in == nil {
		return nil
	}
	out := new(GarageWebUIList)
	in.DeepCopyInto(out)
	return out
}

func (in *GarageWebUIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *GarageWebUISpec) DeepCopyInto(out *GarageWebUISpec) {
	*out = *in
	out.AutoUpdate = in.AutoUpdate
	out.GarageClusterRef = in.GarageClusterRef
	out.Expose = in.Expose
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(WebUIAuthSpec)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

func (in *GarageWebUISpec) DeepCopy() *GarageWebUISpec {
	if in == nil {
		return nil
	}
	out := new(GarageWebUISpec)
	in.DeepCopyInto(out)
	return out
}

func (in *GarageWebUIStatus) DeepCopyInto(out *GarageWebUIStatus) {
	*out = *in
	if in.LastUpdateCheck != nil {
		in, out := &in.LastUpdateCheck, &out.LastUpdateCheck
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *GarageWebUIStatus) DeepCopy() *GarageWebUIStatus {
	if in == nil {
		return nil
	}
	out := new(GarageWebUIStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *GarageWebUIClusterRef) DeepCopyInto(out *GarageWebUIClusterRef) {
	*out = *in
}

func (in *GarageWebUIClusterRef) DeepCopy() *GarageWebUIClusterRef {
	if in == nil {
		return nil
	}
	out := new(GarageWebUIClusterRef)
	in.DeepCopyInto(out)
	return out
}

func (in *RouteSpec) DeepCopyInto(out *RouteSpec) {
	*out = *in
}

func (in *RouteSpec) DeepCopy() *RouteSpec {
	if in == nil {
		return nil
	}
	out := new(RouteSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	out.MetaStorageSize = in.MetaStorageSize.DeepCopy()
	out.DataStorageSize = in.DataStorageSize.DeepCopy()
}

func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *WebUIAuthSpec) DeepCopyInto(out *WebUIAuthSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
}

func (in *WebUIAuthSpec) DeepCopy() *WebUIAuthSpec {
	if in == nil {
		return nil
	}
	out := new(WebUIAuthSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *WebUIExposeSpec) DeepCopyInto(out *WebUIExposeSpec) {
	*out = *in
	out.Route = in.Route
}

func (in *WebUIExposeSpec) DeepCopy() *WebUIExposeSpec {
	if in == nil {
		return nil
	}
	out := new(WebUIExposeSpec)
	in.DeepCopyInto(out)
	return out
}
